name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main # Or your default branch
    paths: ['src/**.puml', '.github/workflows/**.yml'] # Only run if .puml files in src/ change
  workflow_dispatch: # Allows manual triggering

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow action to write to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'zulu', 'adopt', etc.
          java-version: '17' # PlantUML needs Java

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Download PlantUML
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar -O plantuml.jar # Check latest version
      
      - name: Create diagrams directory
        run: mkdir -p diagrams
      
      - name: Generate PNG Diagrams (Manual)
        run: |
          for file in src/*.puml; do
            echo "Processing $file..."
            java -jar plantuml.jar -tpng "$file" -o diagrams # Output png to diagrams/
          done
      - name: Generate SVG Diagrams (Manual) - Uncomment if you prefer SVG
        run: |
          for file in src/*.puml; do
            echo "Processing $file for SVG..."
            java -jar plantuml.jar -tsvg "$file" -o diagrams # Output svg to diagrams/
          done

      - name: Commit and Push diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate PlantUML diagrams"
          file_pattern: 'diagrams/*' # Commit only changes in the diagrams directory