name: Generate PlantUML Diagrams
on:
  workflow_dispatch:

jobs:
  plantuml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Generate SVG Diagrams
        uses: holowinski/plantuml-github-action@main
        with:
          image: holowinski/plantuml:latest
          args: -v -tsvg diagrams/*.puml