name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main # Or your default branch
    paths: ['src/**.puml', '.github/workflows/**.yml'] # Only run if .puml files in src/ change
  workflow_dispatch: # Allows manual triggering

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow action to write to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'zulu', 'adopt', etc.
          java-version: '17' # PlantUML needs Java

      - name: Cache Graphviz
        id: cache-graphviz
        uses: actions/cache@v4
        with:
          path: /usr/bin/dot
          key: ${{ runner.os }}-graphviz

      - name: Install Graphviz
        if: steps.cache-graphviz.outputs.cache-hit != 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

      - name: Cache PlantUML
        id: cache-plantuml
        uses: actions/cache@v4
        with:
          path: plantuml.jar
          key: ${{ runner.os }}-plantuml-1.2024.3

      - name: Download PlantUML
        if: steps.cache-plantuml.outputs.cache-hit != 'true'
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar -O plantuml.jar # Check latest version

      - name: Create diagrams directory
        run: mkdir -p diagrams

      - name: Generate PNG Diagrams
        run: |
          for file in src/*.puml; do
            echo "Processing $file..."
            java -jar plantuml.jar -tpng "$file" -o diagrams # Output png to diagrams/
          done

      - name: Generate SVG Diagrams - Uncomment if you prefer SVG
        run: |
          for file in src/*.puml; do
            echo "Processing $file for SVG..."
            java -jar plantuml.jar -tsvg "$file" -o diagrams # Output svg to diagrams/
          done

      - name: Debug List diagrams directory
        run: ls -la diagrams

      - name: Debug Git status
        run: git status

      - name: Commit and Push diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate PlantUML diagrams"
          file_pattern: 'diagrams/*' # Commit only changes in the diagrams directory
          # Optional: If you want to add the diagrams directory itself to git
          # add_empty_commit: true
