name: Generate PlantUML Diagrams

on:
  push:
    branches:
      - main # Or your default branch
    paths:
      - 'src/**.puml' # Only run if .puml files in src/ change
  workflow_dispatch: # Allows manual triggering

jobs:
  generate_diagrams:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allow action to write to the repository

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Or 'zulu', 'adopt', etc.
          java-version: '17' # PlantUML needs Java

      
      # Option 2: Manual PlantUML Execution (If the action above doesn't work or you need more control)
      - name: Download PlantUML
        run: wget https://github.com/plantuml/plantuml/releases/download/v1.2024.3/plantuml-1.2024.3.jar -O plantuml.jar # Check latest version
      
      - name: Create diagrams directory
        run: mkdir -p diagrams
      
      - name: Generate PNG Diagrams (Manual)
        run: |
          for file in src/*.puml; do
            echo "Processing $file..."
            java -jar plantuml.jar -tpng "$file" -o diagrams # Output png to diagrams/
          done
      - name: Generate SVG Diagrams (Manual) - Uncomment if you prefer SVG
        run: |
          for file in src/*.puml; do
            echo "Processing $file for SVG..."
            java -jar plantuml.jar -tsvg "$file" -o diagrams # Output svg to diagrams/
          done

      # Option 1: Using a dedicated PlantUML Action (Recommended)
      # - name: Generate Diagrams (using action)
      #   uses: cloudbees/plantuml-actions/generate-diagrams@v1.1.0 # Check for latest version
      #   with:
      #     # Location of the PlantUML source files (.puml)
      #     source: "src"
      #     # Location where generated diagrams will be stored
      #     output: "diagrams"
      #     # Optional: Specify output format (png, svg, etc.)
      #     # format: png
      #     # Optional: Include specific config files if needed
      #     # config: plantuml.config
      #     # Optional: Specify PlantUML version if needed
      #     # version: latest

      - name: Commit and Push diagrams
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate PlantUML diagrams"
          file_pattern: 'diagrams/*' # Commit only changes in the diagrams directory
          # Optional: Specify branch if not pushing to the triggering branch
          # push_options: '--force' # Use with caution if needed
